### ISSUE TITLE
파일구조 변경

### ISSUE THREAD

**Issue by HongzCloud** [HongzCloud/VideoConverter#51]
## Work List
- [x] AssetPlayer Class 를 만들어 PlayerViewController의 역할 줄이기 ⬇️
- [x] ViewModel을 생성하여 PlayerViewController의 역할 줄이기 ⬇️

**Comment by BMO5** [comment]
와우!! 잘 리팩토링하시길바래요!

**Comment by HongzCloud** [comment]
> 와우!! 잘 리팩토링하시길바래요!

감사합니다! >ㅁ< ☺️
